### ISSUE TITLE
How can I specify the name/password for the mqtt server in the plugin settings?

### ISSUE THREAD

**Issue by khaidakin** [Luligu/matterbridge-zigbee2mqtt#1]
I installed the matterbridge-zigbee2mqtt plugin, but I don’t understand where I should specify the username/password for connecting to mosquitt in the settings.
Please tell me how to do this correctly?

**Comment by Luligu** [comment]
Is done on GitHub. 
I'm finalizing a few more stuff then I will make a release.

**Comment by khaidakin** [comment]
sudo npm install -g matterbridge-zigbee2mqtt installs the old version 2.0.2
And through git clone... I can’t install 2.0.3 (there are not enough single-plate resources to run npm run build)

**Comment by khaidakin** [comment]
I decided to try installing the new version of matterbridge-zigbee2mqtt on another, more powerful single board computer via git clone.
I still don't have enough resources to run npm install
![2024-03-26_22-31-32](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/59665419/07b8f1cb-f14d-4043-9280-2874049c13ec)

**Comment by Luligu** [comment]
I'm finalizing just be patient.
To load the 2.0.3 you need the new version of matterbridge that contains the DoorLock.
It doesn't transpile without. 
This is why I didn't publish

**Comment by khaidakin** [comment]
The zigbee2mqtt plugin connects to the mqtt server with authorization now. This question is closed.

**Comment by khaidakin** [comment]
The zigbee2mqtt plugin connects to the mqtt server with authorization now. This question is closed.
