### ISSUE TITLE
Inovelli VZM31-SN support

### ISSUE THREAD

**Issue by genehand** [Luligu/matterbridge-zigbee2mqtt#20]
Hey thanks for a great project.  I've been looking for ways to make Alexa -> Home Assistant responses faster, and using matter for local control is definitely the way to go.  Most of my devices are already supported with the exception of the [Inovelli blue](https://www.zigbee2mqtt.io/devices/VZM31-SN.html) light switches.

They show up in the registered devices list as `MA-onofflight (0x0100)`, although I notice the cluster includes button config as well. Maybe this is why Alexa isn't finding it as a standard Matter light?

```OnOff: true Composed: button Level: 152%```

Happy to provide whatever other info you need. Thx!

**Comment by genehand** [comment]
I was able to get these working by adding a FeatureBlackList for `action` then unregistering all the bridged devices 👍

**Comment by Luligu** [comment]
Hi,
thank you for your interest.
I would use
deviceFeatureBlackList cause the featureBlackList apply to all devices. Unless you want to black list all buttons in all devices.
If you need some more support for your device I need the 3 files in .matterbridge directory bridge info device and group.json.

**Comment by genehand** [comment]
Hey what's the best place to send those? I sent a request over on discord
