### ISSUE TITLE
Username and password are required thorugh GUI

### ISSUE THREAD

**Issue by stefan-schweiger** [Luligu/matterbridge-zigbee2mqtt#27]
Username and password are required fields for the UI, but actually they are not needed (if your MQTT host does not have it configured)

<img width="832" alt="image" src="https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/3532342/39fadfc1-428b-4a37-9d66-c3456c241659">

**Comment by Luligu** [comment]
Hi,
you are right.

Please put this updated file in the .matterbridge directory.

It will be solved for every one in the next release.

Thanks.

[matterbridge-zigbee2mqtt.schema.json](https://github.com/user-attachments/files/15867041/matterbridge-zigbee2mqtt.schema.json)
