### ISSUE TITLE
Support transitionTime where applicable  (e.g. transition)

### ISSUE THREAD

**Issue by stefan-schweiger** [Luligu/matterbridge-zigbee2mqtt#28]
Most (if not all) zigbee2mqtt light devices support a [duration/transition time](https://www.zigbee2mqtt.io/devices/17436_30_P7.html#transition) for controlling the dim level and sometimes also color.

As far as I can tell this currently is not exposed / passed through with this plugin. Would be great to have this ability where it applies.

[Here](https://github.com/project-chip/matter.js/blob/732d82813cd29bef69943181d9e44e799dcbc007/packages/matter.js/src/cluster/definitions/LevelControlCluster.ts#L73) is the corresponding definition in matter.js:

**Comment by Luligu** [comment]
Hi,
I agree with you 100 %.
The problem here unfortunately is not what we could do in the plugin, but what we con do right now with the actual versions of the controllers.
There is no controller that send appropriate commands for the duration and transition so there is nothing we can do now.
We are still in a situation where all controllers support (not even completely) Matter 1.1.
The Matter 1.3 specs added a lot of new devices that I would love to see in the controllers and of course add to z2m plugin too...
but we have to wait.
Just to make you an example, Matterbridge had the Air Quality device ready since October last year. I had to wait 8 month before seeing it in a controller (HA in this case). 
All common use new Matter 1.3  devices are already added to Matterbridge but no controllers support them...
If you have found a controller that support more let me know... I will be happier then you to add some new devices and more control over the supported clusters.
Same problem applies to shelly plugin that I'm releasing now. The devices have a lot of functionalities that I cannot use cause the controllers don't support more then On Off Level Color.

**Comment by stefan-schweiger** [comment]
Thank you very much for that detailed explanation. Since I'm not running home assistant myself I don't have too much insight how their controller works, but just from a quick glance at the HA code shouldn't this send the command with the transition time? Or do you mean the actual UI/automations don't support it?

https://github.com/home-assistant/core/blob/71a9ba25dca17a3bd07c46dedcdcfff1ff7228be/homeassistant/components/matter/light.py#L152-L158

**Comment by Luligu** [comment]
{
  level: 130,
  transitionTime: 2,
  optionsMask: { executeIfOff: false, coupleColorTempToLevel: false },
  optionsOverride: { executeIfOff: false, coupleColorTempToLevel: false }
}
This is how the command moveToLevelWithOnOff is sent to our devices from ha. 
You have no option to set the transition in the ha ui.
![image](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/132135057/7f74b59d-b151-48bd-abfa-803597ca36e6)

**Comment by stefan-schweiger** [comment]
It seems a bit weird to me that apparently they just always send `transitionTime: 2`. But what I can gather from the [HA documentation](https://www.home-assistant.io/integrations/light/#service-lightturn_on) (search for transition) it seems like you can either configure a default value for all lights through profiles or use it through automations. For example to create a wakeup light which gets gradually brighter for a duration of like 30 minutes.

**Comment by stefan-schweiger** [comment]
Just set up HA real quick and configured a automation to move the brightness to 80 within 10 seconds and this is what I see in the matterbridge logs:

`Invoke moveToLevelWithOnOff with data {"level":80,"transitionTime":100,"optionsMask":{"executeIfOff":false,"coupleColorTempToLevel":false},"optionsOverride":{"executeIfOff":false,"coupleColorTempToLevel":false}}`

So I think HA does handle this correctly.

**Comment by Luligu** [comment]
Hi,
is done.

Are you available to test it on your setup before I publish?

## [2.0.18] - 2024-06-17

### Added

- [dependencies]: Update dependencies
- [schema]: Added schema to the root directory of the plugin
- [properties]: Added soil_moisture properties as humidity sensor
- [properties]: Added transition if the zigbee device supports it and the controller sends it. You can disable this globally adding transition to the featureBlackList or only for the single device adding transition to the deviceFeatureBlackList.

### Fixed
- [schema]: Username and password are no more required fields
- [LevelControl]: Fixed the commandHandler for LevelControl in child endpoint.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by stefan-schweiger** [comment]
Sure, what's the best way to try out some "prerelease" when running matterbridge in a docker container? Just manually building it on my system and copy the results over in the `Matterbridge/matterbridge-zigbee2mqtt` folder?

**Comment by Luligu** [comment]
I guess you are expert so I usually do this way with my collaborators that use dicker:
- copy the .tgz file in Matterbridge directory (the mapped directory outside the container)
- open a bash shell on the container: docker exec -it matterbridge /bin/bash
- then from the shell: npm -g install ~/Matterbridge/*.tgz

This always work but for sure there are other methods...

[matterbridge-zigbee2mqtt-2.0.18.zip](https://github.com/user-attachments/files/15887170/matterbridge-zigbee2mqtt-2.0.18.zip)

Let me know if you need more help.

Thanks for testing.

## [2.0.18] - 2024-06-17

### Added

- [dependencies]: Update dependencies
- [schema]: Added schema to the root directory of the plugin
- [properties]: Added soil_moisture properties as humidity sensor
- [properties]: Added transition if the zigbee device supports it and the controller sends it. You can disable this globally adding transition to the featureBlackList or only for the single device adding transition to the deviceFeatureBlackList. (Thanks Stefan Schweiger)

### Fixed
- [schema]: Username and password are no more required fields (Thanks Stefan Schweiger)
- [LevelControl]: Fixed the commandHandler for LevelControl in child endpoint (Thanks jpadie).

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by Luligu** [comment]
This work unless you are using a local copy of the plugin..

**Comment by Luligu** [comment]
[matterbridge-1.3.0.zip](https://github.com/user-attachments/files/15887292/matterbridge-1.3.0.zip)

This is matterbridge. You need it before you install z2m plugin

**Comment by stefan-schweiger** [comment]
The transition seems to work fine, so thanks a lot for that! But I'm still seeing the username/password as required for the settings GUI

**Comment by stefan-schweiger** [comment]
Ok seems like the `npm -g install ~/Matterbridge/*.tgz` didn't update the config file, if I manually copy it over it's fine

**Comment by Luligu** [comment]
Yeah I need to publish both cause when you noticed that I was refactoring the loading of schema from .matterbridge to plugin directory. And removing from matterbridge so I don't need to modify matterbridge to modify a plugin schema...

**Comment by Luligu** [comment]
I need to update ColorControl to Matter 1.3 (they changed a few stuff there). After I will add transition also there...
If everything is ok you can close the issue.
Thanks for collaborating with me.

**Comment by stefan-schweiger** [comment]
Thanks again for implementing this so quickly :) let me know once the color control transition is ready then I can test that as well. I will leave the issue upon till then if that's ok for you

**Comment by Luligu** [comment]
I didn't forget the transition on ColorControl...
Just need to publish again Matterbridge (probably if the tests go well tomorrow) and then I will add the transition.

**Comment by Luligu** [comment]
[matterbridge-zigbee2mqtt-2.1.5.zip](https://github.com/user-attachments/files/16058460/matterbridge-zigbee2mqtt-2.1.5.zip)
## [2.1.5] - 2024-07-01

### Changed

- [zigbee]: Fixed WindowCovering.targetPositionLiftPercent100ths update.
- [z2m]: Added transition to ColorControl if the zigbee device supports it and the controller sends it. You can disable this globally adding transition to the featureBlackList or only for the single device adding transition to the deviceFeatureBlackList. (Thanks Stefan Schweiger).

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

Can you please test the transition on ColorControl ?

**Comment by stefan-schweiger** [comment]
Sure, give me a few minutes and I will come back to you!

**Comment by stefan-schweiger** [comment]
Seems to work exactly as expected! Thank you very much again for implementing this.

**Comment by Luligu** [comment]
My pleasure,
one day maybe all the controllers will have the option for transition...
Thanks for testing and for the idea.
