### ISSUE TITLE
Battery Level always showing as 100%

### ISSUE THREAD

**Issue by stefan-schweiger** [Luligu/matterbridge-zigbee2mqtt#46]
I just noticed that the exposed battery level is always 100% (or 200 as the cluster value since it's expressed in 0.5 steps as a uint8). For example in Zigbee2MQTT I see this for my the current device (a Ikea door sensor) state:

```
{
    "ac_status": false,
    "battery": 81,
    "battery_defect": false,
    "battery_low": false,
    "contact": true,
    "linkquality": 188,
    "restore_reports": false,
    "supervision_reports": false,
    "tamper": false,
    "test": false,
    "trouble": false,
    "update": {
        "installed_version": 16777241,
        "latest_version": 16777241,
        "state": "idle"
    }
}
```

But in Matterbridge the following value is shown (which of course is showing up as 100% for example in Home Assistant):

<img width="1712" alt="image" src="https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/3532342/0bf7f8b8-35a7-4d5d-9f8f-5e56001ab7e5">

From quickly looking through the code I can't find anything obviously false with your calculation here:

https://github.com/Luligu/matterbridge-zigbee2mqtt/blob/fca046a26dd5f4b9e8eac95a69ac234b7a5ed84f/src/entity.ts#L544

**Comment by stefan-schweiger** [comment]
One other thing I just noticed for another device which exposes `voltage` I see that the value in Matterbridge is actually half of what it is in Zigbee2MQTT even though the conversion you are doing should not be changing the value:

https://github.com/Luligu/matterbridge-zigbee2mqtt/blob/fca046a26dd5f4b9e8eac95a69ac234b7a5ed84f/src/entity.ts#L549

Is there maybe another conversion happening in matter.js or Matterbridge itself?

**Comment by stefan-schweiger** [comment]
Maybe this conversion?

https://github.com/Luligu/matterbridge/blob/e9b5a46f2822a51aa43241ff253952f7d582b671/src/matterbridgeDevice.ts#L2412

https://github.com/Luligu/matterbridge/blob/e9b5a46f2822a51aa43241ff253952f7d582b671/src/matterbridgeDevice.ts#L2453

Not sure why voltage then would be half since I don't see a similar thing for battery voltage. But maybe there is another problem since my voltage is 3000 and the default value is 1500 (= half of 3000), so maybe the voltage is not handled at all.

**Comment by Luligu** [comment]
Hi,
for the batter level:
            /**
             * This attribute shall indicate the estimated percentage of battery charge remaining until the battery
             * will no longer be able to provide power to the Node. Values are expressed in half percent units, ranging
             * from 0 to 200. E.g. a value of 48 is equivalent to 24%. A value of NULL shall indicate the Node is
             * currently unable to assess the value.
             *
             * @see {@link MatterSpecification.v11.Core} § 11.7.6.13
             */
So matterbridge do correctly multiply the percentage by 2. The controller is wrong to show the value, I will check other controllers ... just to be sure.

**Comment by stefan-schweiger** [comment]
@Luligu I think you by accident multiple by 2 twice (once in matterbridge-zigbee and once in matterbridge), and since you cap the value at 200 it will always show as 100%. Probably if the battery is below 25% values below 100% would show up.

**Comment by Luligu** [comment]
I have this
![image](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/132135057/59167ca6-4648-4697-86a2-41db983ae1ad)
that shows in this way
![image](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/132135057/3b943b3e-9627-4000-ac5c-314e53614d0f)

I don't understand what you mean ?

**Comment by Luligu** [comment]
![image](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/132135057/73bcc8e3-36c0-4fa1-8a03-9db38e835ec4)
![IMG_9689](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/132135057/b8d9389d-f8b4-4ffe-9bd2-57a94fc169f0)
They match
![image](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/132135057/7a5903d0-9e2a-4e17-bc67-81a65e8418d4)
![IMG_9690](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/132135057/45290648-4131-47b2-9108-41a1d2c5e54f)
They match too

Keep in mind that what you see in the state in z2m can be a situation of moths ago... z2m doesn't publish it again unless you enable send state on start-up and restart...

**Comment by stefan-schweiger** [comment]
I have 100% for **every** device in Matterbridge/HA:

<img width="1118" alt="image" src="https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/3532342/d5f350f4-1835-43b8-afa1-b201997d746f">

But in Zigbee2MQTT they are sensible:

<img width="1403" alt="image" src="https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/3532342/dd79980c-c573-432a-8500-9d1e9f2d8cd5">

**Comment by stefan-schweiger** [comment]
> Keep in mind that what you see in the state in z2m can be a situation of moths ago... z2m doesn't publish it again unless you enable send state on start-up and restart...

Can you go into more detail what this means? I see a [few config options](https://www.zigbee2mqtt.io/guide/configuration/mqtt.html#mqtt-behaviour) which might fit, but the other zigbee2mqtt integrations I have been using until now where fine with the default config, so I'm a bit unsure why it wouldn't work

**Comment by Luligu** [comment]
State in z2m is like photo of last settings registered maybe in the last year. 
Doesn't mean that those values are sent-published. 
This option decide what happens with state
![image](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/132135057/2ba2ccdf-380d-4b3e-acea-c0a9967bcc1a)

If all is enabled you can try to restart z2m and it should send the state again. Then check the matterbridge log to see the values update go through ... like Update endpoint.

Is possible that HA doesn't show correctly the values. Apple does as you saw.

**Comment by Luligu** [comment]
I made the same test... I guess HA doesn't divide by 2...
Enable the dynamic example plugin and pair with HA ... there all devices have different kind of batteries and level so you can check what HA does...

**Comment by stefan-schweiger** [comment]
I have all of those options enabled (which is the default) and restarrted zigbee2mqtt but nothing changed.

Just to be clear HA is only reflecting what it gets from Matterbridge. All values in Matterbridge are actually 200 for me.

<img width="534" alt="image" src="https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/3532342/6d87d582-b2f1-4b14-9635-9c1a57f10a3e">

**Comment by Luligu** [comment]
The data are not sent then...

**Comment by stefan-schweiger** [comment]
The devices from `matterbridge-example-dynamic-platform` all show up with correct battery values

**Comment by Luligu** [comment]
Then z2m is not sending values...
In the gui Logs put the name of your device in the search box and let it run the whole night... then check if it has updates...

**Comment by Luligu** [comment]
Hi, 
in HA you can ask to reinterview device on the aggregator. Then HA reload all attributes, battery included.

**Comment by stefan-schweiger** [comment]
> Hi, in HA you can ask to reinterview device on the aggregator. Then HA reload all attributes, battery included.

Maybe lets leave HA out of the picture, as far as I can tell the values are just reflecting what Matterbridge provides and they update correctly.

> Then z2m is not sending values...
> In the gui Logs put the name of your device in the search box and let it run the whole night... then check if it has updates...

After letting it sit all night I have the correct battery values. Then I tried to restart Matterbridge and everything went back to 200. I have now also tired to enable `device_options: { retain: true }` so the broker always keeps the last state of the device (not sure if there is any downsides to this besides storage though), but seems like Matterbridge also does not pick up those retained messages on startup.

**Comment by Luligu** [comment]
Hi,
the retain has no effect on this. It is just useful for the bridge messages that are retained so you can know the z2m status even if z2m is stopped.
If you want to update Matter attributes without waiting the battery devices to connect and publish, you can simply leave Matterbridge running and restart z2m (providing you have the option to send state on start activated).
