### ISSUE TITLE
[FeatureRequest] Expose device as temperature sensor

### ISSUE THREAD

**Issue by FreAcX** [Luligu/matterbridge-zigbee2mqtt#52]
It would be great if there was an option to expose devices as a temperature sensor. 
Just like with the lightlist and outletlist. In my case, Alexa is used a lot to query room temperatures.
Sometimes the sensors of the Hue motion detectors are used instead of separate temperature sensors.
However, as these are exposed as motion detectors, they cannot be used in this way.

**Comment by tammeryousef1006** [comment]
try using blacklist feature of a device , its in the end of z2m config , in case you got a device that has detection sensor and temp sensor but only detection exposed , then you can blacklist that feature and get the temp to be exposed

**Comment by Luligu** [comment]
Like this:
<img width="597" alt="image" src="https://github.com/user-attachments/assets/c95272dc-a026-4e74-ae06-16cd4274f4bb">
