### ISSUE TITLE
Matterbridge zigbee2mqtt plugin reports reports Unacceptable protocol version

### ISSUE THREAD

**Issue by hubecker** [Luligu/matterbridge-zigbee2mqtt#55]
My zigbee2mqtt is configured to connect to my FHEM [https://fhem.de/](url) mqtt server.
So i configured Matterbridge zigbee2mqtt  the same way, but i am getting the following error:

`error - [16:00:30.810] [Zigbee2MQTT]: Error connecting to mqtt://192.168.178.242:1883: Connection refused: Unacceptable protocol version
error - [16:00:30.810] [Matterbridge zigbee2mqtt plugin]: MQTT broker at 192.168.178.242:1883 error: ErrorWithReasonCode: Connection refused: Unacceptable protocol version
error - [16:00:36.744] [Matterbridge zigbee2mqtt plugin]: The plugin did not receive zigbee2mqtt bridge state. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [16:00:36.744] [Matterbridge zigbee2mqtt plugin]: The plugin did not receive zigbee2mqtt bridge info. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [16:00:36.744] [Matterbridge zigbee2mqtt plugin]: The plugin did not receive zigbee2mqtt bridge devices/groups. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [16:00:36.744] [PluginManager]: Failed to start plugin matterbridge-zigbee2mqtt: Error: The plugin did not receive zigbee2mqtt bridge state or info or devices/groups. Check if zigbee2mqtt is running and connected to the MQTT broker.
e`

zigbee2mqtt  has no problem to connect to the mqtt server
What is the problem here and how can we solve it?

regards

Hubert

**Comment by Luligu** [comment]
Hi,
sorry for the late answer, I'm currently on holiday.
I will analyse this and I guess I can add to the config the protocol version.
Can you send me please your configuration.yaml?

**Comment by hubecker** [comment]
Hi,
Thanks for the answer.  Right now i am also on holiday, so i can't send you my configuration.yaml.
But configured the bridge from the UI:
My MQTT host is like this mqtt://192.168.178.XX:1883, no user, no password.
As far as i know the FHEM MQTT Server supports only protocol version 4. I think configuring the protocol version would be a good way to solve this problem.
Thanks for you help.

**Comment by Luligu** [comment]
Hi,
give it a try when you can please.

## [2.1.12] - 2024-08-21

### Changed

- [schema]: Changed schema file to add MQTT protocol.
- [schema]: Changed descriptions in schema for easier setup.
- [package]: Updated dependencies.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by hubecker** [comment]
Hi,
i tied with protocoll version 3 and 4 but iam still getting the error
`info - [17:38:03.893] [Matterbridge]: WebSocketServer client "::ffff:192.168.178.122" connected to Matterbridge
error - [17:38:03.897] [Zigbee2MQTT]: Error connecting to mqtt://192.168.178.242:1883: Connection refused: Unacceptable protocol version
error - [17:38:03.897] [Matterbridge zigbee2mqtt plugin]: MQTT broker at 192.168.178.242:1883 error: ErrorWithReasonCode: Connection refused: Unacceptable `


`error - [17:38:13.929] [Matterbridge zigbee2mqtt plugin]: The plugin did not receive zigbee2mqtt bridge state. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [17:38:13.929] [Matterbridge zigbee2mqtt plugin]: The plugin did not receive zigbee2mqtt bridge info. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [17:38:13.929] [Matterbridge zigbee2mqtt plugin]: The plugin did not receive zigbee2mqtt bridge devices/groups. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [17:38:13.929] [PluginManager]: Failed to start plugin matterbridge-zigbee2mqtt: Error: The plugin did not receive zigbee2mqtt bridge state or info or devices/groups. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [17:38:14.600] [Matterbridge]: The plugin matterbridge-zigbee2mqtt is in error state.
error - [17:38:14.600] [Matterbridge]: The bridge will not start until the problem is solved to prevent the controllers from deleting all registered devices.
error - [17:38:14.601] [Matterbridge]: If you want to start the bridge disable the plugin in error state and restart.
`

How can we debug this in more detail?

both matterbridge and plugins are at latest version.

regards

Hubert

**Comment by Luligu** [comment]
I found the bug in the new patch...

Publish tomorrow after test,

Unless you know how to install from a .tgz file.

**Comment by Luligu** [comment]
## [2.1.13] - 2024-08-22

### Changed

- [package]: Updated dependencies.

### Fixed

- [package]: Fixed MQTT protocol.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by hubecker** [comment]
Hi,
It is kind of working now, but is going into error state:
`info - [16:19:24.837] [PluginManager]: Starting plugin matterbridge-zigbee2mqtt type DynamicPlatform
info - [16:19:24.837] [Matterbridge zigbee2mqtt plugin]: Starting zigbee2mqtt dynamic platform v2.1.13: The plugin has been enabled
debug - [16:19:25.548] [Zigbee2MQTT]: Connection established
debug - [16:19:25.548] [Zigbee2MQTT]: Started
info - [16:19:25.548] [Matterbridge zigbee2mqtt plugin]: MQTT broker at 192.168.178.242:1883 connected
debug - [16:19:25.548] [Zigbee2MQTT]: Subscribing topic: zigbee2mqtt/#
debug - [16:19:25.552] [Zigbee2MQTT]: Subscribe success on topic: zigbee2mqtt/#
info - [16:19:25.553] [Matterbridge zigbee2mqtt plugin]: MQTT broker at 192.168.178.242:1883 subscribed to: zigbee2mqtt/#
error - [16:19:39.837] [Matterbridge zigbee2mqtt plugin]: The plugin did not receive zigbee2mqtt bridge state. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [16:19:39.838] [Matterbridge zigbee2mqtt plugin]: The plugin did not receive zigbee2mqtt bridge info. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [16:19:39.838] [Matterbridge zigbee2mqtt plugin]: The plugin did not receive zigbee2mqtt bridge devices/groups. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [16:19:39.838] [PluginManager]: Failed to start plugin matterbridge-zigbee2mqtt: Error: The plugin did not receive zigbee2mqtt bridge state or info or devices/groups. Check if zigbee2mqtt is running and connected to the MQTT broker.
error - [16:19:39.838] [PluginManager]: Plugin matterbridge-zigbee2mqtt not started
debug - [16:19:49.300] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:19:52.094] [Zigbee2MQTT]: Message for ***unknown*** entity: BMAnkleidezimmer service: payload: {"battery":100,"devi ... ufacturerName":"IKEA of Sweden","model":"E21 ... 303,"state":"idle"}}
debug - [16:20:11.518] [Zigbee2MQTT]: Message for ***unknown*** entity: AquaraH2 service: payload: {"auto_off":false,"b ... 52,"powerSource":"DC Source","stackVersio ... "},"voltage":233.31}
debug - [16:20:25.549] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:20:42.095] [Zigbee2MQTT]: Message for ***unknown*** entity: BMAnkleidezimmer service: payload: {"battery":100,"devi ... ufacturerName":"IKEA of Sweden","model":"E21 ... 303,"state":"idle"}}
debug - [16:20:49.301] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:21:01.519] [Zigbee2MQTT]: Message for ***unknown*** entity: CP.Rauchmelder service: payload: {"ac_status":false," ... lse,"trouble":false}
debug - [16:21:25.549] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:21:29.169] [Zigbee2MQTT]: Message for ***unknown*** entity: BMEingang service: payload: {"battery":84,"devic ... 831,"state":"idle"}}
debug - [16:21:32.530] [Zigbee2MQTT]: Message for ***unknown*** entity: BMEingang service: payload: {"battery":84,"devic ... 831,"state":"idle"}}
debug - [16:21:42.276] [Zigbee2MQTT]: Message for ***unknown*** entity: Repeater1 service: payload: {"device":{"applicat ... ufacturerName":"IKEA of Sweden","model":"E1746","networkAddress":5777,"powerSource":"Mains (single phase)","softwareBui ... 409,"state":"idle"}}
debug - [16:21:42.276] [Zigbee2MQTT]: Message for ***unknown*** entity: BMAnkleidezimmer service: payload: {"battery":100,"devi ... ufacturerName":"IKEA of Sweden","model":"E21 ... 303,"state":"idle"}}
debug - [16:21:49.301] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:22:25.549] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:22:37.643] [Zigbee2MQTT]: Message for ***unknown*** entity: BMEingang service: payload: {"battery":84,"devic ... 831,"state":"idle"}}
debug - [16:22:37.643] [Zigbee2MQTT]: Message for ***unknown*** entity: BMEingang service: payload: {"battery":84,"devic ... 831,"state":"idle"}}
debug - [16:22:46.538] [Zigbee2MQTT]: Message for ***unknown*** entity: BMEingang service: payload: {"battery":84,"devic ... 831,"state":"idle"}}
debug - [16:22:49.303] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:22:51.712] [Zigbee2MQTT]: Message for ***unknown*** entity: BMAnkleidezimmer service: payload: {"battery":100,"devi ... ufacturerName":"IKEA of Sweden","model":"E21 ... 303,"state":"idle"}}
debug - [16:22:56.510] [Zigbee2MQTT]: Message for ***unknown*** entity: BMEingang service: payload: {"battery":84,"devic ... 831,"state":"idle"}}
debug - [16:23:01.938] [Zigbee2MQTT]: Message for ***unknown*** entity: BMAnkleidezimmer service: payload: {"battery":100,"devi ... ufacturerName":"IKEA of Sweden","model":"E21 ... 303,"state":"idle"}}
debug - [16:23:06.548] [Zigbee2MQTT]: Message for ***unknown*** entity: BMEingang service: payload: {"battery":84,"devic ... 831,"state":"idle"}}
debug - [16:23:08.156] [Zigbee2MQTT]: Message for ***unknown*** entity: BMEingang service: payload: {"battery":84,"devic ... 831,"state":"idle"}}
debug - [16:23:11.341] [Zigbee2MQTT]: Message for ***unknown*** entity: BMHue service: payload: {"battery":23.5,"dev ... 831,"state":"idle"}}
debug - [16:23:25.549] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:23:49.304] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:23:51.585] [Zigbee2MQTT]: Message for ***unknown*** entity: BMEingang service: payload: {"battery":84,"devic ... 831,"state":"idle"}}
debug - [16:24:01.821] [Zigbee2MQTT]: Message for ***unknown*** entity: BMAnkleidezimmer service: payload: {"battery":100,"devi ... ufacturerName":"IKEA of Sweden","model":"E21 ... 303,"state":"idle"}}
info - [16:24:02.612] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 28 devices
debug - [16:24:02.613] [Zigbee2MQTT]: Received 24 devices
debug - [16:24:02.613] [Zigbee2MQTT]: handleEvent() type: device_announce name: BMEingang address: 0x0017880106476bce
info - [16:24:02.613] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent device_announce device: BMEingang ieee_address: 0x0017880106476bce
debug - [16:24:02.613] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-devices.json
info - [16:24:02.621] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 28 devices
debug - [16:24:02.623] [Zigbee2MQTT]: Received 24 devices
debug - [16:24:02.623] [Zigbee2MQTT]: handleEvent() type: device_announce name: BMEingang address: 0x0017880106476bce
info - [16:24:02.623] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent device_announce device: BMEingang ieee_address: 0x0017880106476bce
debug - [16:24:02.623] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-devices.json
info - [16:24:02.700] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 28 devices
debug - [16:24:02.701] [Zigbee2MQTT]: Received 24 devices
debug - [16:24:02.701] [Zigbee2MQTT]: handleEvent() type: device_announce name: BMEingang address: 0x0017880106476bce
info - [16:24:02.701] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent device_announce device: BMEingang ieee_address: 0x0017880106476bce
info - [16:24:02.704] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 28 devices
debug - [16:24:02.705] [Zigbee2MQTT]: Received 24 devices
debug - [16:24:02.705] [Zigbee2MQTT]: handleEvent() type: device_announce name: BMEingang address: 0x0017880106476bce
info - [16:24:02.705] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent device_announce device: BMEingang ieee_address: 0x0017880106476bce
debug - [16:24:02.706] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-devices.json
debug - [16:24:02.706] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-devices.json
debug - [16:24:25.549] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:24:49.305] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:25:25.549] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:25:49.306] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:26:25.549] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:26:49.306] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:27:25.549] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:27:49.306] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:28:25.549] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:28:49.306] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:29:25.550] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:29:49.305] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:30:25.551] [Zigbee2MQTT]: Publishing keepalive MQTT message
debug - [16:30:49.306] [Zigbee2MQTT]: Publishing keepalive MQTT message
info - [16:31:19.391] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 28 devices
debug - [16:31:19.391] [Zigbee2MQTT]: Received 24 devices
debug - [16:31:19.392] [Zigbee2MQTT]: handleEvent() type: device_announce name: BMEingang address: 0x0017880106476bce
info - [16:31:19.392] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent device_announce device: BMEingang ieee_address: 0x0017880106476bce
info - [16:31:19.395] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 28 devices
debug - [16:31:19.395] [Zigbee2MQTT]: Received 24 devices
debug - [16:31:19.395] [Zigbee2MQTT]: handleEvent() type: device_announce name: BMEingang address: 0x0017880106476bce
info - [16:31:19.395] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent device_announce device: BMEingang ieee_address: 0x0017880106476bce
debug - [16:31:19.396] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-devices.json
debug - [16:31:19.396] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-devices.json
info - [16:31:22.980] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 28 devices
debug - [16:31:22.980] [Zigbee2MQTT]: Received 24 devices
debug - [16:31:22.980] [Zigbee2MQTT]: handleEvent() type: device_announce name: BMEingang address: 0x0017880106476bce
info - [16:31:22.980] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent device_announce device: BMEingang ieee_address: 0x0017880106476bce
info - [16:31:22.984] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 28 devices
debug - [16:31:22.984] [Zigbee2MQTT]: Received 24 devices
debug - [16:31:22.984] [Zigbee2MQTT]: handleEvent() type: device_announce name: BMEingang address: 0x0017880106476bce
info - [16:31:22.984] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent device_announce device: BMEingang ieee_address: 0x0017880106476bce
debug - [16:31:22.985] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-devices.json
debug - [16:31:22.985] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-devices.json
debug - [16:31:25.551] [Zigbee2MQTT]: Publishing keepalive MQTT message`

Also i have a mqtt device in FHEM, which is from my perpective the matterbridge-zigbee2mqtt client, There is a field 
heartbeat  with the value alive.
So i guess the mqtt connection is now working.

It looks like the plugin is getting 24 devices, but they don't show up and the status is error


regards

Hubert

**Comment by Luligu** [comment]
Hi,
if you are using the latest 1.4.3, we can try to use the new functions:
set debug and log to file
![image](https://github.com/user-attachments/assets/df4aa3a9-2292-49d3-928c-d9e4e3617dde)
then restart and wait a few minutes
then send me the matterbridge log
![image](https://github.com/user-attachments/assets/49759cd2-4493-4bd4-9d65-18f4763198ff)

Thanks.
