### ISSUE TITLE
govee2mqtt -> mosquitto -> matterbridge (not working)

### ISSUE THREAD

**Issue by psdl-dev** [Luligu/matterbridge-zigbee2mqtt#63]
First of all - Thanks for your great work. :)

I have installed matterbridge and mosquitto as mqtt broker with docker compose. I then installed govee2mqtt (wez). This also finds my Govee lamp and reports to mosquitto with the zigbee topic “govee2mqtt/xxxxxxx...”. Unfortunately, I cannot see the lamp in the Matterbridge. I think it is because the Matterbridge expects a topic “zigbee2mqtt”. Is this the problem? And how can I fix it? Any help is welcome. (I can't change the topic in govee2mqtt, i think it is hardcoded.

**Comment by Luligu** [comment]
Hi,
thanks for your appreciation.
I don't think that your lamp sends the same data as zigbee2mqtt...
If you want to try, you can change the topic in the plugin config.

**Comment by psdl-dev** [comment]
The Addon is working with the home assistant zigbee2mqtt and mosquitto setup. So i thought it should work the the mosquitto setup from your docker container. It also contacts the mosquitto broker successfully, but i don't see anything in the matterbridge.

**Comment by Luligu** [comment]
Hi,
yes the data format are not the same of course.
