### ISSUE TITLE
Grouping of Thermostats -> Lights

### ISSUE THREAD

**Issue by psdl-dev** [Luligu/matterbridge-zigbee2mqtt#67]
I am grouping two Thermostats in Zigbee2mqtt. The Matterbridge will only recognize the group with Device-Type: "MA-onofflight (0x0100)". But it should be: "MA-thermostat (0x0301)".

**Comment by psdl-dev** [comment]
Cool ! :) Do you need more information ?

**Comment by Luligu** [comment]
I have a thermostat from moes in my setup so I guess I could test with it and after ask you. to test on your setup.
But it will not be soon...

**Comment by Luligu** [comment]
Hi,
I'm releasing 2.2.0 that includes an enhancement to the group.
I added Covers and I was adding the Thermostat but in my setup the group with thermostat doesn't really work.
It does not accept the command published.
Did you try in your group of thermostats if the group accept the commands like current_heating_setpoint and execute them on grouped devices?
