### ISSUE TITLE
Disable/Hide Certain Attributes

### ISSUE THREAD

**Issue by nitaybz** [Luligu/matterbridge-zigbee2mqtt#7]
Thanks a lot for the effort of making this plugins, I've been tested it to see it works well and very happy that this integration exists :)

One thing that I've found as missing is the ability to disable certain attributes from being published. for example:
Light switch that comes with "action" attribute that I don't need.
Rolling Shutter with device "temperature" attribute that is no good for me.

It would be great if we could hide/disable certain attributes from being published/shown on a device level or even wide system level.

I've tried messing with zigbee2Mqtt to prevent the device from publishing this attribute and it indeed happens but the devices still showing the action attribute, even after restarts, uninstalls and deleting the config files. it seems like this plugin is taking the configurations from Z2M configurations and it shows there that this attribute exist.

much appreciations.

**Comment by Luligu** [comment]
Hi,
thank you for your interest. 
I appreciate it.

Point 1 and 2
You are right this feature is already in my homebridge plugin (https://github.com/Luligu/mqtt-accessories). I moved here too.
Will be up in the next release.

Point 3
You get it correctly, I read the exposes. 

What controller are you using? I'm looking for some tests with Google or Alexa...

This is what will in the next release.

## [2.0.7] - 2024-04-10

### Added
- [config.featureBlackList] Features with name in the list will be ignored (e.g. device_temperature) (https://github.com/nitaybz).
- [config.switchList] Device with friendly name in the list will be exposed like switch.
- [config.lightList] Device with friendly name in the list will be exposed like light.
- [config.outletList] Devices with friendly name in the list will be exposed like outlet.

### Fixed

- [payload]: Fixed the case when z2m sends null or undefined in the payload (https://github.com/khaidakin).

**Comment by nitaybz** [comment]
That's great news!
Can't wait to test it.

Regarding your questions. I have all platforms in my house. Apple Home, Home Assistant, Google Home and Alexa.
I mostly use HomeKit as the dashboard and home assistant as the brain of the automations and scenes. But I can test your plugin in any of these platforms.

And by the way, if you are a homebridge plugin developer, and familiar with the matterbridge, I would love to see a matterbridge-homebridge plugin that will get all accessories from Homebridge and pair them as Matthew accessories :)

**Comment by Luligu** [comment]
Great to hear this.
I have no knowledge of how Matter is supported in Alexa and Google Home. It would be interesting to understand it.
Thanks.

**Comment by Luligu** [comment]
Hi,
the new release is published on npm.
Update matterbridge first and after matterbridge-zigbee2mqtt.

**Comment by nitaybz** [comment]
I just checked it out and it works great, thanks!

**Comment by nitaybz** [comment]
suggestion: add the option to block certain attributes for certain devices. instead of blocking it system wide.
for example block temperature reading of Philips Hue Motion Sensor (since there is another one that is more accurate). or block the "action" for some devices but allow some buttons to appear.

**Comment by Luligu** [comment]
Hi,
sounds good. 
The exclusion was meant to be for features like device_temperature or power_outage etc.. not for the main features like action.
