### ISSUE TITLE
Presence Sensor is not showing

### ISSUE THREAD

**Issue by nitaybz** [Luligu/matterbridge-zigbee2mqtt#8]
Hi,

I've noticed that presence sensors with attribute "presence" are not showing.
Is it possible to make it appear as occupancy sensors?

also, I see all my motion sensor shows as occupancy sensor, I know that's because Z2M does not have "motion" attribute but it marks it all as "occupancy" but I would really love to have the option to change their type to "Motion Sensor" in order to distinguish between presence sensors (Occupancy) to Motion Sensors.

Maybe you can add more lists to config:
"motionList", "occupancyList", "contactList".

**Comment by Luligu** [comment]
Hi,
In Matter is not like hap. You have only one OccupancySensing. 
For the presence you are right.
Will be fixed in the next release.
Thanks.
Can you send me the 3 files: bridge-*.json in Home\Matterbridge\matterbridge-zigbee2mqtt and the name of your device that use presence please?

**Comment by Luligu** [comment]
I made it but I would prefer to check the files...
Will in the next release.
