### ISSUE TITLE
Missing mandatory field transitionTime

### ISSUE THREAD

**Issue by nicandris** [Luligu/matterbridge-zigbee2mqtt#80]
Hey, whenever I try to change brightness I get this message and Google assistant shows "something went wrong" (setting the log level to debug doesn't show anything more)

`info - [08:07:38.966] [InteractionServer]: Validation-Error 0x80 while invoking command: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime in field transitionTime`

device details also show level 254%
`OnOff: false Level: 254% X: 0 Y: 0 Hue: 0 Saturation: 0% ColorTemp: 420`

To be honest I have no idea when this started, I rarely play around with brightness

**Comment by Luligu** [comment]
Hi,
we already undestood this issues there:
https://github.com/Luligu/matterbridge-shelly/issues/65

I agree with Apollon: please report to Google! They need to fix this not compliant behavior.

**Comment by Apollon77** [comment]
@nicandris Do you also use a preview firmware for the google nest device?

**Comment by nicandris** [comment]
yeah i was on most of my Google homes. i left the preview program (not sure if it actually worked) but still the same

**Comment by Apollon77** [comment]
So which firmware are the devices having?

**Comment by nicandris** [comment]
nest minis and nest audio: 437716
nest hub: 20.20240530.3.18053

**Comment by Apollon77** [comment]
so seems to be this preview firmware

**Comment by Luligu** [comment]
I added a link to this issue to the matterbridge README and I post it on the new issues with the same reasons...
Thanks @nicandris
