### ISSUE TITLE
[Bug] Matterbridge.loadInstance() failed with error: Error: [node-persist][readFile] does not look like a valid storage file!

### ISSUE THREAD

**Issue by Slyke** [Luligu/matterbridge-zigbee2mqtt#82]
Hello, getting this error:
```
[09:36:28.414] [Matterbridge] Matterbridge is starting...
CLI: Matterbridge.loadInstance() failed with error: Error: [node-persist][readFile] /root/.matterbridge/storage/.matterbridge/92cd10e6b8b068a931196d1d73a032543d5ca1a5bf445e27a1af74258254517c does not look like a valid storage file!
```

Version: `v.1.5.10`

When I inspect this file manually, I see that it is an empty 0kb file.

Other files in the same directory contain JSON blobs, such as:
```
{"key":"matterbridgeLatestVersion","value":"1.5.10"}
```

Deleting the empty file and restarting the pod seems to fix the error. I'm not sure what caused the empty file, but I suspect that it's crashing because it couldn't parse an empty file as JSON.

**Comment by Luligu** [comment]
Hi,
this happens when for a power outage or hardware failure the storage get corrupted (also possible if your setup kill the process while it is writing).

If you have a backup you can manually restore it.

From 1.6.1 of matterbridge (currently under test) there will be an automatic backup of both storage and an automatic restore of both storage unless you pass -norestore on the command line. This should solve the damaged storage issues in unattended setups.

My best.

**Comment by Slyke** [comment]
Yep, it's possible the node was not shut down correctly. There was a power outage and my UPS ran out.

Will the automatic restore happen even if the file exists, but is unreadable? If so, awesome.

**Comment by Luligu** [comment]
Hi,
The new code will try to open both storages and, if the call doesn't fail, will make a backup to be eventually used the next run. In this process the code will do a check of each key of node storage and if any call fails will restore the previous backup.
The check is abstract... if the key is valid it will succeed... there is always the possibility that the key is damaged but readable. But in my experience when the storage open fails is always for 0 length files or keys. This usually happens for whatever reason kill the process while writing: power outages or hardware/system failures.

**Comment by Slyke** [comment]
Do you want me to close this issue? I'll update to `v1.6.1` once it's released.

**Comment by Luligu** [comment]
## [1.6.1] - 2024-11-01

### Added

- [matterbridge]: Added automatic recovery for matterbridge node storage when it gets corrupted for a power outage or hardware failure. Unattended setups can automatically recover restoring the previous automatic backup.
- [matterbridge]: Added automatic recovery for matter storage when it gets corrupted for a power outage or hardware failure. Unattended setups can automatically recover restoring the previous automatic backup.
- [matterbridge]: Added parameter "-norestore" to force not to restore automatically. In this case you need to manually restore a full backup made from the frontend.

### Changed

- [package]: Update dependencies.

### Fixed

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by Luligu** [comment]
You can close sure if you are happy with the answer... :D

**Comment by Luligu** [comment]
I guess the case is fixed with auto recovery...
