### ISSUE TITLE
No converter available for 'current_heating_setpoint'

### ISSUE THREAD

**Issue by nicandris** [Luligu/matterbridge-zigbee2mqtt#83]
Hey I get this error in z2m when i change the temperature of a [thermostatic radiator valve](https://www.zigbee2mqtt.io/devices/TRVZB.html)

Matterbridge
`info - [16:38:43.518] [Matterbridge zigbee2mqtt plugin]: MQTT publish topic: zigbee2mqtt/radiator/set message: {"current_heating_setpoint":25}`

Zigbee2MQTT
`error 2024-11-08 17:38:43z2m: No converter available for 'current_heating_setpoint' (25)`

I'm assuming the correct one would be `occupied_heating_setpoint`

Sample device state
```
{
    "battery": 85,
    "child_lock": "UNLOCK",
    "closing_steps": 389,
    "frost_protection_temperature": 7,
    "idle_steps": 198,
    "last_seen": "2024-11-08T17:41:52+01:00",
    "linkquality": 204,
    "local_temperature": 23,
    "local_temperature_calibration": 0,
    "occupied_heating_setpoint": 23,
    "open_window": "OFF",
    "running_state": "idle",
    "system_mode": "heat",
    "update": {
        "installed_version": 4609,
        "latest_version": 4609,
        "state": "idle"
    },
    "valve_closing_degree": 100,
    "valve_closing_limit_voltage": 3036,
    "valve_motor_running_voltage": 1441,
    "valve_opening_degree": 100,
    "valve_opening_limit_voltage": 2268,
    "weekly_schedule": {
        "friday": "00:00/16 07:00/19 10:00/16 10:00/16 17:00/19 23:00/16",
        "monday": "00:00/16 07:00/19 10:00/16 10:00/16 17:00/19 23:00/16",
        "saturday": "00:00/16 07:00/19 10:00/19 10:00/19 10:00/19 23:00/16",
        "sunday": "00:00/16 07:00/19 10:00/19 10:00/19 10:00/19 23:00/16",
        "thursday": "00:00/16 07:00/19 10:00/16 10:00/16 17:00/19 23:00/16",
        "tuesday": "00:00/16 07:00/19 10:00/16 10:00/16 17:00/19 23:00/16",
        "wednesday": "00:00/16 07:00/19 10:00/16 10:00/16 17:00/19 23:00/16"
    },
    "elapsed": 2508
}
```

**Comment by Luligu** [comment]
Hi,
thank for your interest.

I see the issue there...

apparently on z2m there is no standard in naming the features...
the thermo I used to develop is this one https://www.zigbee2mqtt.io/devices/BHT-002_BHT-006.html#moes-bht-002-bht-006
and it uses current_heating_setpoint

I will think how to check and support both features...

**Comment by fiftysomethingguy** [comment]
I have the same problem with my thermostat. It also uses occupied_heating_setpoint. So when MQTT sends a message it doesn't update the status if I change the setpoint on the device and it doesn't change the setpoint on the device if I change it in my Matter Controller.

 [19:29:51.442] [Hive Thermostat]: MQTT message for device Hive Thermostat payload: { linkquality: 69, local_temperature: 23.07, max_heat_setpoint_limit: 32, min_heat_setpoint_limit: 5, occupied_heating_setpoint: 23, running_state: 'idle', system_mode: 'heat', temperature_setpoint_hold: true, temperature_setpoint_hold_duration: 213, weekly_schedule: { days: [ 'saturday' ], transitions: [ { heating_setpoint: 23, time: 510 }, { heating_setpoint: 1, time: 1380 }, { heating_setpoint: 1, time: 1380 }, { heating_setpoint: 1, time: 1380 }, { heating_setpoint: 1, time: 1380 }, { heating_setpoint: 1, time: 1380 } ] } }

[19:29:51.444] [Hive Thermostat]: Update endpoint MA-thermostat:17 attribute Thermostat-localTemperature from 2276 to 2307

The device is https://www.zigbee2mqtt.io/devices/SLR1c.html

Also the Matter exposed thermostat doesn't repsect the min and max capable temperatures it just sets them to 0C and 50C

**Comment by Luligu** [comment]
Hi,
I will try to find a way to deal with the differet properties of the thermostats in z2m.
Thanks for reaching out.

**Comment by Luligu** [comment]
Hi,
I made an enhancement for that.

Is it possible for you two to test it before I publish?

Can you join the discord group so I can send you a tgz to install?

**Comment by fiftysomethingguy** [comment]
How do I join the discord group?

**Comment by Luligu** [comment]
https://github.com/Luligu/matterbridge/blob/main/CHANGELOG.md#discord

**Comment by nicandris** [comment]
> Hi, I made an update for that.
> 
> Is it possible for you two to test it before I publish?
> 
> Can you join the discord group so I can send you a tgz to install?

i missed this but I've seen the release, I'll check anw and let you know later
