### ISSUE TITLE
issue with motion devices that expose temp & humd

### ISSUE THREAD

**Issue by tammeryousef1006** [Luligu/matterbridge-zigbee2mqtt#9]
hi

- after adding all devices to smartthings hub , i noticed that motion devices which report also temperature  are showing only the temperature ( smartthings Motion sensor (2018 model) ) and not showing the motion part , i got other motion devices are working correctly (sonoff SNZB-03 ) , is there any workaround to show the motion sensor as priority ahead of temperature ?
- i got the tab for the log but it doesnt report transactions even its set to info .
- as a question is it possible to add the functions like reset bridge and reset child bridge to the gui web page beside shutdown and reboot functions ? also if possible to add an info regarding which controllers already commissioned to the bridge (such as home assistant , google home etc.. ) with the ability to remove controller from same page .
kindly see below from the smartthings app and zigbee2mqtt pages

Best Regards 

![Screenshot_20240418_175331_SmartThings](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/62266828/50835122-d873-4419-bbf5-9e6a30919e7f)
![Screenshot_20240418_175302_SmartThings](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/62266828/2e0c1efe-5382-4672-ad95-9ef701b156c2)
 and from zigbee2mqtt
![kids motion](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/62266828/85002a59-a66b-4e45-b3cd-9c3a378cecec)
![ewelink motion](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/62266828/48c9fe93-5baf-4447-8ea6-270ac176be44)

**Comment by Luligu** [comment]
Hi,I’m with only phone, but can you send me please the 3 file bridge info devices and group that are in the Matterbridge/matterbridge-zigbee2mqtt directory. I need to see the expose.For log problem (randomly connecting) the patch is already done and  will publish this night but I would like to solve the first problem too…The rest are excellent ideas will be in the todo list.Thanks On 18 Apr 2024, at 17:06, Tamer Salah ***@***.***> wrote:﻿
hi

after adding all devices to smartthings hub , i noticed that motion devices which report also temperature and humidity are showing only the temperature and humidity ( smartthings Motion sensor (2018 model) ) and not showing the motion part , i got other motion devices are working correctly (sonoff SNZB-03 ) , is there any workaround to show the motion sensor as priority ahead of temperature ?
i got the tab for the log but it doesnt report transactions even its set to info .
as a question is it possible to add the functions like reset bridge and reset child bridge to the gui web page beside shutdown and reboot functions ? also if possible to add an info regarding which controllers already commissioned to the bridge (such as home assistant , google home etc.. ) with the ability to remove controller from same page .
kindly see below from the smartthings app

Best Regards
Screenshot_20240418_175331_SmartThings.jpg (view on web)
Screenshot_20240418_175302_SmartThings.jpg (view on web)
and from zigbee2mqtt
kids.motion.png (view on web)
ewelink.motion.png (view on web)

**Comment by Luligu** [comment]
For the controller question can you send me the number you see in the log and tell me what controlle is it ?

[20:07:26.720] [Matterbridge] Controller 4937/Windows connected to Matterbridge 
I know that 4937 is Apple Home and Windows is the name of the Home.
If you can give me the information about the numbers of the other most used controllers I can add them and it's a nice idea.

**Comment by Luligu** [comment]
If you want to try the pre release and test it contact me on Discord where I can send you the pre release.

**Comment by tammeryousef1006** [comment]
I will reply with more details once i reach home . The controller is
smartthings v3 hub

**Comment by tammeryousef1006** [comment]
im using smartthings hub and this what i got from the log  :
[Matterbridge] Controller 4362/SmartThings Hub 1B52 connected to
Matterbridge

**Comment by tammeryousef1006** [comment]
failed to send so i had to compress it

**Comment by tammeryousef1006** [comment]
[bridge-devices.json](https://github.com/Luligu/matterbridge-zigbee2mqtt/files/15030910/bridge-devices.json)
[bridge-groups.json](https://github.com/Luligu/matterbridge-zigbee2mqtt/files/15030911/bridge-groups.json)
[bridge-info.json](https://github.com/Luligu/matterbridge-zigbee2mqtt/files/15030912/bridge-info.json)
[networkmap_raw.json](https://github.com/Luligu/matterbridge-zigbee2mqtt/files/15030913/networkmap_raw.json)

**Comment by tammeryousef1006** [comment]
hello , how to find and contact you at discord ?

**Comment by Luligu** [comment]
Hi,I published the new releases both Matterbridge and z2m plugin…Added also Smarthings to the controller names…When you have time check the wss connection please (the logs).On discord same name as GitHub…We speak there for your motion device with temperature… but I checked the files and it seems perfect. I will load it in the simulator just to be sure.Thanks for your help.On 19 Apr 2024, at 13:14, Tamer Salah ***@***.***> wrote:﻿
hello , how to find and contact you at discord ?

**Comment by Luligu** [comment]
The featureBlackList allows to blacklist a z2m feature if you don't want to expose it (e.g. device_temperature).
